### ISSUE TITLE
Create pypi repository

### ISSUE THREAD

**Issue by Aerendel** [AllenCell/napari-allencell-segmenter#10]
**Story**
As the Institute, I want to distribute the plugin to users under a recognizable name so that people know where it's coming from

**A/C**

- Repository created in pypi and owned by AICS

**Details**
- Package name = `napari-allencell-segmenter`
- Make sure we use the proper AICS pypi account

**Comment by Kimcmetzler** [comment]
- Package name = napari-allencell-segmenter
