### ISSUE TITLE
No plugin found error message when loading CZI file for segmentation testing

### ISSUE THREAD

**Issue by derekthirstrup** [AllenCell/napari-allencell-segmenter#103]
Both AICS segmentation and napari are capable of loading CZI files but I get an error message when trying to test the segmenter plugin with a CZI file.  Does pylibczi work with napari segmenter plugin?

**Comment by Aerendel** [comment]
@derekthirstrup this error means that Napari doesn't know how to load a CZI file - so it's got nothing to do with the Segmenter plugin. Have you successfully loaded CZI files in Napari before? If so there must be another plugin you might have installed to get that working.

**Comment by Aerendel** [comment]
Opened #105 for this.
