### ISSUE TITLE
Need to support aicsimageio v4

### ISSUE THREAD

**Issue by schoinh** [AllenCell/napari-allencell-segmenter#117]
## Description
At the end of June, the [aicsimageio napari plugin (napari-aicsimageio) started to use aicsimageio v4](https://github.com/AllenCellModeling/napari-aicsimageio/releases/tag/v0.3.0) under the hood, but the aicsimageio version we use for this segmenter plugin is pinned to <4. This makes the napari plugins napari-aicsimageio and napari-allencell-segmenter incompatible to use together.

Fixing this bug might also resolve #116 

## Expected Behavior
napari-allencell-segmenter needs to support aicsimageio v4

## Reproduction
1. Install and open napari in a fresh virtual environment
2. Install the napari-aicsimageio plugin
3. Install the napari-allencell-segmenter plugin
4. Open the "Show status" button in the napari plugin installation window. Error message as follows:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
napari-aicsimageio 0.3.5 requires aicsimageio[all]~=4.0.2, but you have aicsimageio 3.3.7 which is incompatible.
Successfully installed aicsimageio-3.3.7 aicspylibczi-2.8.0 napari-allencell-segmenter-1.0.3 readlif-0.3.1
```
You can see above that installing napari-allencell-segmenter downgrades aicsimageio in the virtual environment from v4 to v3.3.7.

## Environment
Reproduced on Mac/Python 3.9 and Windows

_Originally posted by @schoinh in https://github.com/AllenCell/napari-allencell-segmenter/issues/116#issuecomment-897887946_

**Comment by yrkim98** [comment]
This is fixed if we unpin the <4 version on aicsimageio in the napari-aicssegmentation repo

**Comment by schoinh** [comment]
Great. I'll close this issue then!
