### ISSUE TITLE
Napari Allen Cell and Structure Segmenter -- Edge Preserve Smoothing

### ISSUE THREAD

**Issue by Rohanpatel1012** [AllenCell/napari-allencell-segmenter#146]
When running the workflows for any process that has Edge Preserve Smoothing I get an error message as follow:

  90     # via the itk_base_global_module_data instance defined at the bottom of this file, which
     91     # knows how to find those configuration files.
---> 92     l_data = itk_base_global_module_data[name]
        l_data = undefined
        global itk_base_global_module_data = {'ITKAnisotropicSmoothing': <itk.support.base.ITKModuleInfo object at 0x7fc8693783a0>, 'ITKAntiAlias': <itk.support.base.ITKModuleInfo object at 0x7fc8693784f0>, 'ITKBiasCorrection': <itk.support.base.ITKModuleInfo object at 0x7fc86938be20>, 'ITKBinaryMathematicalMorphology': <itk.support.base.ITKModuleInfo object at 0x7fc86939e250>, 'ITKBridgeNumPy': <itk.support.base.ITKModuleInfo object at 0x7fc8b82a0310>, 'ITKClassifiers': <itk.support.base.ITKModuleInfo object at 0x7fc8b82abc70>, 'ITKColormap': <itk.support.base.ITKModuleInfo object at 0x7fc8b82b4dc0>, 'ITKCommon': <itk.support.base.ITKModuleInfo object at 0x7fc8b82d3f70>, 'ITKConnectedComponents': <itk.support.base.ITKModuleInfo object at 0x7fc8b82d6a60>, 'ITKCurvatureFlow': <itk.support.base.ITKModuleInfo object at 0x7fc880f041f0>, 'ITKDeconvolution': <itk.support.base.ITKModuleInfo object at 0x7fc880f19c70>, 'ITKDisplacementField': <itk.support.base.ITKModuleInfo object at 0x7fc8b82b0880>, 'ITKDistanceMap': <itk.support.base.ITKModuleInfo object at 0x7fc8a314a130>, 'ITKEigen': <itk.support.base.ITKModuleInfo object at 0x7fc8381ba610>, 'ITKFastMarching': <itk.support.base.ITKModuleInfo object at 0x7fc8381d4d60>, 'ITKFiniteDifference': <itk.support.base.ITKModuleInfo object at 0x7fc8381d4fd0>, 'ITKIOBMP': <itk.support.base.ITKModuleInfo object at 0x7fc8381e68b0>, 'ITKIOBioRad': <itk.support.base.ITKModuleInfo object at 0x7fc8381f19a0>, 'ITKIOBruker': <itk.support.base.ITKModuleInfo object at 0x7fc8381f1bb0>, 'ITKIOGDCM': <itk.support.base.ITKModuleInfo object at 0x7fc8381f1d90>, 'ITKIOGE': <itk.support.base.ITKModuleInfo object at 0x7fc8381f1f70>, 'ITKIOGIPL': <itk.support.base.ITKModuleInfo object at 0x7fc8381f7190>, 'ITKIOHDF5': <itk.support.base.ITKModuleInfo object at 0x7fc8381f73a0>, 'ITKIOIPL': <itk.support.base.ITKModuleInfo object at 0x7fc8381f74c0>, 'ITKIOImageBase': <itk.support.base.ITKModuleInfo object at 0x7fc8381f79a0>, 'ITKIOJPEG': <itk.support.base.ITKModuleInfo object at 0x7fc8381f77c0>, 'ITKIOJPEG2000': <itk.support.base.ITKModuleInfo object at 0x7fc8e01faee0>, 'ITKIOLSM': <itk.support.base.ITKModuleInfo object at 0x7fc8e01faf70>, 'ITKIOMINC': <itk.support.base.ITKModuleInfo object at 0x7fc8e01ff0d0>, 'ITKIOMRC': <itk.support.base.ITKModuleInfo object at 0x7fc8e01ff580>, 'ITKIOMeshBYU': <itk.support.base.ITKModuleInfo object at 0x7fc8e01ff760>, 'ITKIOMeshBase': <itk.support.base.ITKModuleInfo object at 0x7fc8e01ff940>, 'ITKIOMeshFreeSurfer': <itk.support.base.ITKModuleInfo object at 0x7fc880f298e0>, 'ITKIOMeshGifti': <itk.support.base.ITKModuleInfo object at 0x7fc8e02062b0>, 'ITKIOMeshOBJ': <itk.support.base.ITKModuleInfo object at 0x7fc8e02063a0>, 'ITKIOMeshOFF': <itk.support.base.ITKModuleInfo object at 0x7fc8e02064f0>, 'ITKIOMeshVTK': <itk.support.base.ITKModuleInfo object at 0x7fc8e02068e0>, 'ITKIOMeta': <itk.support.base.ITKModuleInfo object at 0x7fc8e0206ac0>, 'ITKIONIFTI': <itk.support.base.ITKModuleInfo object at 0x7fc8e0206ca0>, 'ITKIONRRD': <itk.support.base.ITKModuleInfo object at 0x7fc8e0206e80>, 'ITKIOPNG': <itk.support.base.ITKModuleInfo object at 0x7fc8e0206d00>, 'ITKIORAW': <itk.support.base.ITKModuleInfo object at 0x7fc8e020d2b0>, 'ITKIOSiemens': <itk.support.base.ITKModuleInfo object at 0x7fc8e020d4c0>, 'ITKIOSpatialObjects': <itk.support.base.ITKModuleInfo object at 0x7fc8e020d8b0>, 'ITKIOStimulate': <itk.support.base.ITKModuleInfo object at 0x7fc8e020db20>, 'ITKIOTIFF': <itk.support.base.ITKModuleInfo object at 0x7fc8e020dcd0>, 'ITKIOTransformBase': <itk.support.base.ITKModuleInfo object at 0x7fc8e020dfa0>, 'ITKIOTransformHDF5': <itk.support.base.ITKModuleInfo object at 0x7fc8e02141f0>, 'ITKIOTransformInsightLegacy': <itk.support.base.ITKModuleInfo object at 0x7fc8e02143d0>, 'ITKIOTransformMatlab': <itk.support.base.ITKModuleInfo object at 0x7fc8e02144f0>, 'ITKIOVTK': <itk.support.base.ITKModuleInfo object at 0x7fc8e0214700>, 'ITKImageCompare': <itk.support.base.ITKModuleInfo object at 0x7fc8e02148b0>, 'ITKImageCompose': <itk.support.base.ITKModuleInfo object at 0x7fc8e0214d30>, 'ITKImageFeature': <itk.support.base.ITKModuleInfo object at 0x7fc8381fb0d0>, 'ITKImageFilterBase': <itk.support.base.ITKModuleInfo object at 0x7fc8381fbc70>, 'ITKImageFrequency': <itk.support.base.ITKModuleInfo object at 0x7fc8382193d0>, 'ITKImageFunction': <itk.support.base.ITKModuleInfo object at 0x7fc8691b49d0>, 'ITKImageFusion': <itk.support.base.ITKModuleInfo object at 0x7fc8691b4d90>, 'ITKImageGradient': <itk.support.base.ITKModuleInfo object at 0x7fc8c0e29520>, 'ITKImageIntensity': <itk.support.base.ITKModuleInfo object at 0x7fc8c0e29d00>, 'ITKImageLabel': <itk.support.base.ITKModuleInfo object at 0x7fc8c0e37e80>, 'ITKImageNoise': <itk.support.base.ITKModuleInfo object at 0x7fc8a31b0c40>, 'ITKImageStatistics': <itk.support.base.ITKModuleInfo object at 0x7fc8a31c2790>, 'ITKLabelMap': <itk.support.base.ITKModuleInfo object at 0x7fc8a31c9760>, 'ITKLabelVoting': <itk.support.base.ITKModuleInfo object at 0x7fc8306dc700>, 'ITKLevelSets': <itk.support.base.ITKModuleInfo object at 0x7fc87221cdc0>, 'ITKMathematicalMorphology': <itk.support.base.ITKModuleInfo object at 0x7fc8722239a0>, 'ITKMesh': <itk.support.base.ITKModuleInfo object at 0x7fc872247340>, 'ITKMetricsv4': <itk.support.base.ITKModuleInfo object at 0x7fc8c1224d60>, 'ITKNarrowBand': <itk.support.base.ITKModuleInfo object at 0x7fc8a31f5820>, 'ITKOptimizers': <itk.support.base.ITKModuleInfo object at 0x7fc8691d9880>, 'ITKOptimizersv4': <itk.support.base.ITKModuleInfo object at 0x7fc8691e0100>, 'ITKPDEDeformableRegistration': <itk.support.base.ITKModuleInfo object at 0x7fc8691e09a0>, 'ITKPath': <itk.support.base.ITKModuleInfo object at 0x7fc8691ed7f0>, 'ITKPyBase': <itk.support.base.ITKModuleInfo object at 0x7fc8691f68e0>, 'ITKPyUtils': <itk.support.base.ITKModuleInfo object at 0x7fc8691fe370>, 'ITKQuadEdgeMesh': <itk.support.base.ITKModuleInfo object at 0x7fc869207190>, 'ITKQuadEdgeMeshFiltering': <itk.support.base.ITKModuleInfo object at 0x7fc869207580>, 'ITKRegionGrowing': <itk.support.base.ITKModuleInfo object at 0x7fc869212220>, 'ITKRegistrationCommon': <itk.support.base.ITKModuleInfo object at 0x7fc869212df0>, 'ITKRegistrationMethodsv4': <itk.support.base.ITKModuleInfo object at 0x7fc871760e80>, 'ITKSignedDistanceFunction': <itk.support.base.ITKModuleInfo object at 0x7fc8717824c0>, 'ITKSmoothing': <itk.support.base.ITKModuleInfo object at 0x7fc8a3218790>, 'ITKSpatialObjects': <itk.support.base.ITKModuleInfo object at 0x7fc8a3218ac0>, 'ITKStatistics': <itk.support.base.ITKModuleInfo object at 0x7fc8a3226100>, 'ITKSuperPixel': <itk.support.base.ITKModuleInfo object at 0x7fc8a3238820>, 'ITKTestKernel': <itk.support.base.ITKModuleInfo object at 0x7fc8a3270310>, 'ITKTransform': <itk.support.base.ITKModuleInfo object at 0x7fc8a327eeb0>, 'ITKVTK': <itk.support.base.ITKModuleInfo object at 0x7fc8a3282e80>, 'ITKVoronoi': <itk.support.base.ITKModuleInfo object at 0x7fc8a3298be0>, 'ITKWatersheds': <itk.support.base.ITKModuleInfo object at 0x7fc8a329c880>, 'MeshToPolyData': <itk.support.base.ITKModuleInfo object at 0x7fc8a329caf0>}
        name = 'ITKImageGrid'
     93     if l_data:
     94         deps = l_data.get_module_dependencies()

KeyError: 'ITKImageGrid'

Please let me know any way to fix this!

**Comment by yrkim98** [comment]
Hi, Could you give me the full stack trace, python version, and operating system so I can take a closer look? Thanks!
