### ISSUE TITLE
Installation Fails on Apple M1 machine

### ISSUE THREAD

**Issue by dgmccart** [AllenCell/napari-allencell-segmenter#147]
## Description
Installing the plugin with pip fails on my Apple M1 machine

### Error message
```
 ERROR: Failed building wheel for numpy
      Failed to build numpy
      ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
```
The full error can be read [here](https://gist.github.com/dgmccart/0e781670fbe00d3215423be4fc808c3f).

## Expected Behavior
The plugin to install.

## Reproduction
*Please list the exact steps we can take to reproduce this bug.*
1. Create a clean conda virtual environment
2. Install napari version 0.4.16 with conda-forge
3. Attempt to pip install the plugin

## Environment
- Operating system (ex. MacOS Big Sur): 
- Python version (ex. 3.8): 3.9
- napari version (ex. 0.4.1): 0.4.16
- How did you install the napari viewer (as a bundled app or through command line with `pip`)?: conda-forge

**Comment by yrkim98** [comment]
This is quite odd- but I will investigate further. I am on a m1 macbook as well and creating a fresh environment running python 3.9, followed by a conda-forge installation of napari and a pip installation of napari-allencell-segmenter does not generate any bugs for me.

**Comment by dgmccart** [comment]
What version of napari installed? I installed 0.4.16 in another fresh environment and encountered the same error. Here are all the commands I ran:
```
conda create -y -n napari-env -c conda-forge python=3.9
conda activate napari-env
conda install -c conda-forge napari=0.4.16
pip install napari-allencell-segmenter
```

**Comment by yrkim98** [comment]
Could you try installing napari-allencell-segmenter after installing numpy like this? This should install numpy without any errors for a M1 macbook.
```
conda update napari
pip3 install Cython
pip3 install --no-binary :all: --no-use-pep517 numpy
pip3 install pandas
pip3 install ib_insync
```
Let me know if that works.

**Comment by yrkim98** [comment]
@dgmccart  this is now resolved
