### ISSUE TITLE
Provide fully compatible test images for end to end testing

### ISSUE THREAD

**Issue by Aerendel** [AllenCell/napari-allencell-segmenter#16]
**Story**
As a stakeholder, I want to make sure the plugin is 100% compatible with the data we release to the public

**A/C**
I know this is done when...

- I have access to a full set of fully vetted test images that pass metadata validation

**Details:**

- We want at least 1 image for each available Segmenter workflow (JianXu to select)
- Ensure images can properly load in Napari
- Image(s) should be of similar nature to the ones released on CFE
- Provide enough test images to cover different scenarios as needed

**Comment by toloudis** [comment]
I did some work on this here:
https://github.com/AllenCell/quilt-data-access-tutorials/blob/feature/test_validation/hipsc_single_cell_image_dataset/Tutorial%203%20-%20Get%20one%20example%20FOV%20from%20each%20cell%20line.ipynb

Added a new branch (feature/test_validaton) that runs validation on each file.  
Currently it seems that validation is passing (which surprised me!) but it also seemed to bring up a possible bug in ome-types which is reported here:
https://github.com/tlambert03/ome-types/issues/68

**Comment by toloudis** [comment]
sample files from ATP2A2, and HIST1H2BJ, SLC2A517, SMC1A, SON, are failing ome validation.
