### ISSUE TITLE
Save workflow - Improve user experience for naming new workflow file

### ISSUE THREAD

**Issue by schoinh** [AllenCell/napari-allencell-segmenter#99]
## Use Case
On my first time using the "Save workflow" button to save a workflow, I specified the workflow file name as "sec61_workflow" (I didn't input "sec61_workflow.json" because I thought .json was already specified in the box below), and I got this error upon saving: "ValueError: Workflow configuration file save path must have a .json extension."

## Solution
The above error message makes sense to me as a developer but for general users we should have an actual error message pop up (instead of a console error that makes it look like they broke something). OR we just attach a `.json` extension to the end of the file name specified if they didn't specify anything.

**Comment by Aerendel** [comment]
As discussed, we want to:
- Put in .json filename placeholder
- Attach .json to the filename if no extension provided or another extension
